services:
  - type: web
    name: hindi-panchang
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
